CREATE DATABASE Clase02;
GO
USE Clase02;
GO
CREATE TABLE Empleados(
    IDEmpleado INT NOT NULL,
    Apellidos VARCHAR(255) NOT NULL,
    Nombres VARCHAR(255) NOT NULL,
    SALARIO DECIMAL NOT NULL,
    FechaContratacion DATE NOT NULL,
    IDArea SMALLINT NULL,
);


CREATE TABLE Areas(
    IDArea SMALLINT NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    Mail VARCHAR(255) NOT NULL
);

GO
-- RESTRICCIONES

ALTER TABLE Empleados
ADD CONSTRAINT PK_Empleados PRIMARY KEY (IDEmpleado);
GO

ALTER TABLE Areas 
ADD CONSTRAINT PK_Areas PRIMARY KEY(IDArea)
GO

ALTER TABLE Empleados
ADD CONSTRAINT CHK_SalarioPositivo CHECK (Salario > 0);
GO 

ALTER TABLE Empleados
ADD CONSTRAINT FK_EmpleadosAreas FOREIGN KEY (IDArea) REFERENCES Areas(IDArea);
GO

-- MODIFICACION DE COLUMNAS

ALTER TABLE Empleados
DROP COLUMN SALARIO;
GO

ALTER TABLE Empleados
ADD Salario DECIMAL NOT NULL;
GO

-- no funciona para cambios de nombre
ALTER TABLE Areas
ALTER COLUMN Telefono VARCHAR(30) NULL;
GO

-- CREACION DE COLUMNAS

ALTER TABLE Empleados ADD Telefono VARCHAR(20) NULL;
GO

ALTER TABLE Areas ADD Telefono VARCHAR(20) NULL;
GO

ALTER TABLE Empleados DROP COLUMN Telefono;
GO
